theme: jekyll-theme-primer
title: Tech Leadership Templates
description: Curated templates showcasing technology leadership practices.



include:
  - templates
collections:
  templates:
    output: true
    
