# Site settings
title: Tech Leadership Templates
description: Explore practical templates demonstrating technology leadership, delivery management, and engineering excellence.
baseurl: ""   # leave empty if using https://username.github.io/repo-name
url: "https://nankam123.github.io/tech-leadership-templates"

# Collections
collections:
  templates:
    output: true     # render pages for this collection
    permalink: /templates/:path/   # URL structure

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
